EVG-16501: clean up error message style
mongodb/anser pull request #61
Opened 2022-03-31 19:35 UTC by Kimchelly

Jira: https://jira.mongodb.org/browse/EVG-16501

* Clean up error message style.

2022-04-06 16:47 UTC, julianedwards requested changes

2022-04-06 16:47 UTC, julianedwards commented on bsonutil/tags.go
> +		panic(fmt.Sprintf("field '%s' cannot have an empty bson tag", fieldName))
`BSON`

2022-04-06 16:47 UTC, julianedwards commented on dependency_network.go
> +			catcher.Add(fmt.Errorf("dependency '%s' is not defined", id))
`catcher.Errorf`

2022-04-06 16:47 UTC, julianedwards commented on environment.go
> +	catcher.NewWhen(!q.Info().Started, "cannot set up anser environment with a non-running queue")
`Anser`

2022-04-06 21:00 UTC, Kimchelly commented on environment.go
> +	catcher.NewWhen(!q.Info().Started, "cannot set up anser environment with a non-running queue")
Done.

2022-04-07 20:39 UTC, julianedwards approved these changes

2022-04-08 16:46 UTC, merged